name: Feature request
description: Suggest an enhancement for DTDE
title: "feat: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement. Please describe the problem first, then the solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like DTDE to do?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, screenshots, benchmarks, etc.
    validations:
      required: false
