name: Question / Support
description: Ask a question about DTDE usage
title: "question: "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        If this is a bug, please use the Bug Report template.

  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you building? Include relevant snippets/config (without secrets).
    validations:
      required: false
