# Release Drafter
# Automatically drafts release notes based on PR labels
# https://github.com/release-drafter/release-drafter

name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    # Only draft releases on push to main, but label PRs always
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
